In [ ]:
.0-axis=columns
1-axis=rows# in numpy

# 1-Dimensional

In [3]:
import numpy as np

a=np.array([10,20,30])  #create a rank 1 array
print(type(a))          #prints "<class 'numpy'>"
print(a.shape)          #print"(3,)""

<class 'numpy.ndarray'>
(3,)


In [4]:
print(a)

[10 20 30]


In [5]:
print(a[0])

10


In [6]:
a[0] = 50
a

array([50, 20, 30])

# 2-Dimension

In [7]:
b= np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print(b.shape)

(2, 3)


In [9]:
print(b[1,2],b[0,1])

6 2


In [10]:
b[0,1]

2

# 3-Dimensional

In [11]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
print(c.shape)

(3, 3)


In [13]:
print(c[2,0])

7


In [14]:
c[1,2]

6

# Numpy also provides many functions to create array

In [15]:
a=np.zeros((2,2))
print(a)
a.shape

[[0. 0.]
 [0. 0.]]


(2, 2)

In [16]:
b=np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
c=np.full((3,3),3)
print(c)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [18]:
d=np.eye(6)
print(d)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [19]:
e=np.random.random((3,2))
print(e)


[[0.63059705 0.35392957]
 [0.14700044 0.53424733]
 [0.52201315 0.78414614]]


In [20]:
f=np.arange(0,21,3)
f

array([ 0,  3,  6,  9, 12, 15, 18])

In [21]:
g=np.linspace(0,6,10)
g

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [23]:
import numpy as np
arr=np.array([[1,2,3,4],
              [5,2,4,2],
              [1,2,0,1]])
newarr=arr.reshape(2,2,3)
print("\nOriginal array:\n",arr)
print("Reshaped array:\n",newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [24]:
a=np.array([[1,2,3],[4,5,6]])
flarr=a.flatten()
print("\nOriginal array:\n",a)
print("Fattened array:\n",flarr)


Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


# Array indexing

# Slicing array

In [25]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])# 1-Dimension
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
b=a[0:2,1:3]
b

array([[2, 3],
       [6, 7]])

In [35]:
print(a[1,1])

6


In [26]:
a[0, 1]=77
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
row_r1=a[2,:]
row_r2=a[1,:]
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)

[ 9 10 11 12] (4,)
[5 6 7 8] (4,)


In [39]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
a[0,]

array([1, 2, 3, 4])

In [41]:
col_r1=a[:, 1]
col_r1

array([ 2,  6, 10])

In [42]:
col_r2=a[:, 2]
col_r2

array([ 3,  7, 11])

In [43]:
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)


[ 9 10 11 12] (4,)
[5 6 7 8] (4,)


# Integer array indexing

In [45]:
a=np.array([[-1,2,0,4],
           [4,-0.5,6,0],
           [2.6,0,7,8],
           [3,-7,4,2.0]])
a

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [46]:
temp=a[[0,1,2,3],[3,2,1,0]]
print("\n Element at indices (0,3),(1,2),(2,1)"
     "(3,0):\n",temp)


 Element at indices (0,3),(1,2),(2,1)(3,0):
 [4. 6. 0. 3.]


# Boolean array

In [48]:
a

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [49]:
cond=a>0
cond

array([[False,  True, False,  True],
       [ True, False,  True, False],
       [ True, False,  True,  True],
       [ True, False,  True,  True]])

In [51]:
cond=a%2==0
temp=a[cond]
print("\n Element greater than 0\n",temp)


 Element greater than 0
 [2. 0. 4. 4. 6. 0. 0. 8. 4. 2.]


# Operations

In [53]:
a=np.array([1,2,5,3])
print("Original element:",a)

print("Adding 1 to every element:",a+1)

print("Subtracting 3 from every element:",a-3)

print("Multiplying each element by 10:",a*10)

print("Squaring each element:",a**2)

a *=2
print("Doubled each element of original array:",a)

a=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("\nOriginal array:\n",a)
print("Transpose of array:\n",a.T)


Original element: [1 2 5 3]
Adding 1 to every element: [2 3 6 4]
Subtracting 3 from every element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [56]:
arr=np.array([[1,5,6],
             [4,7,2],
             [3,1,9]])

print("Largest element is:",arr.max())
print("Row-wise maximum element:",
     arr.max(axis=1))

print("Column-wise maximum elements:",arr.max(axis=0))

print("Sum of all array element:",arr.sum())

print("cumulative sum along each row:\n",arr.cumsum(axis=1))

Largest element is: 9
Row-wise maximum element: [6 7 9]
Column-wise maximum elements: [4 7 9]
Sum of all array element: 38
cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [58]:
a=np.array([[1,2],
           [3,4]])
b=np.array([[4,3],
           [2,1]])

print("Array sum:\n",a+b)

print("Array multiplication:\n",a*b)

print("Matrix multiplication:\n",a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [59]:
a=np.array([25,16,4,9])
print("Exponent of array element:",np.log(a))

print("Square root of array elements:",np.sqrt(a))

Exponent of array element: [3.21887582 2.77258872 1.38629436 2.19722458]
Square root of array elements: [5. 4. 2. 3.]


# Sorting Array:There is a simple np.sort method gor sorting bit

In [60]:
a=np.array([[1,4,2],
           [3,4,6],
           [0,-1,5]])

print("Array elements in sorted order:\n",np.sort(a,axis=None))

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]


In [61]:
print("Column-wise sorted array:\n",np.sort(a, axis=0))

Column-wise sorted array:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [62]:
print("Row wise sort by applying merge-sort:\n",np.sort(a,axis=1))

Row wise sort by applying merge-sort:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
